services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/surveydb
      MONGO_URI: mongodb://mongodb:27017/survey-ai
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: surveydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
